### ISSUE TITLE
Format in projets channel

### ISSUE THREAD

**Issue by rick-gnous** [Rom1-J/tuxbot-bot#10]
An user tried to send a message in projet, with various formats, and it has been always deleted. 

He used the formats: (I’ve anonymized the messages):

```
[link]

[desc]
=========
[desc]
=========
[desc]

[link]
=========
[category]
[desc]

[link]
=========
[category] [desc]

[link]
```

Perhaps a more flexible format should be used?

**Comment by Rom1-J** [comment]
[category] description http://link

ex: ``
[regex] useful regex tester: https://regexcom``
